# HiveKeepers - project - docker-compose.yaml
# written by: Andrew McDonald
# initial: 27/01/22
# current: 2/02/22
# version: 0.8

version: '3.3'

# build containers
services:
  container1:
    build:
      context: container1
      dockerfile: Dockerfile
    container_name: 'reverse-proxy'
    volumes:
      # nginx basic_auth cred file
      - './container1/nginx/auth/.htpasswd:/etc/nginx/auth/.htpasswd'
    restart: "unless-stopped"
    networks:
      container_net:
        ipv4_address: 172.75.0.2
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    ports:
      - '80:80'
      - '443:443'

  container2:
    build:
      context: container2
      dockerfile: Dockerfile
    container_name: 'dash-app'
    volumes:
      # dash app files
      - './container2/dash_app/hivekeepers_app.py:/dash_app/app.py'
      - './container2/dash_app/requirements.txt:/dash_app/requirements.txt'
      - './container2/dash_app/sync_data_202201231041.csv:/dash_app/data.csv'
    restart: "unless-stopped"
    networks:
      container_net:
        ipv4_address: 172.75.0.3
    mem_limit: 6000m

# build container network to control access to containers
networks:
    container_net:
      name: container_net
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.75.0.0/16
